formatting:
  MaximumLineLength:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

style:
  ForbiddenComment:
    values: ['FIXME:', 'STOPSHIP:']
  MaxLineLength:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
